katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import add_task_ajax, add_todolist, delete_task, delete_task_ajax, set_status, show_json, show_todolist
from todolist.views import register #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import logout_user

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create_task/', add_todolist, name='add_todolist'),
    path('delete_task/<int:id>/', delete_task, name='delete_task'),
    path('set_status/<int:id>/', set_status, name='set_status'),
    path('json/', show_json, name='show_json'),
    path('add_task_ajax/', add_task_ajax, name='add_task_ajax'),
    path('delete/<int:id>/', delete_task_ajax, name='delete_task_ajax'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=50)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class CreateTask(forms.Form):
    title = forms.CharField(label='Title')
    description = forms.CharField(label='Description')

todolist/views.py
import datetime
from todolist.models import Task
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.http.response import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist_user = Task.objects.filter(user=request.user)
    context = {
        'data_todolist': data_todolist_user,
        'user_name': request.user
    }
    return render(request, "todolist.html", context)

def delete_task(request,id):
    task = Task.objects.filter(user=request.user).get(pk=id)
    task.delete()
    return redirect('todolist:show_todolist')

def set_status(request,id):
    task = Task.objects.filter(user=request.user).get(pk=id)
    if task.is_finished == False:
        task.is_finished = True
    else:
        task.is_finished = False

    task.save()
    return redirect('todolist:show_todolist')

def add_todolist(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        add_todolist = Task(
            user = request.user,
            title = title,
            description = description,
        )
        add_todolist.save()
        return redirect('todolist:show_todolist')
    return render(request, 'addtodolist.html')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', task), content_type='application/json')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task_ajax(request):
    if request.method == 'POST':
        date = datetime.datetime.now()
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user
        task = Task(user=user, date=date, title = title, description = description)
        task.save()

        output = {
            'pk':task.pk,
            'fields':{
                'title':task.title,
                'description':task.description,
                'is_finished':task.is_finished,
                'date':task.date,
            }
        }
        return JsonResponse(output)

@csrf_exempt
def delete_task_ajax(request,id):
    task = Task.objects.filter(pk=id)   
    task.delete()
    return JsonResponse({"task": "todolist dihapus"})

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Tambahkan Task Kamu</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Kamu mau ngapain hari ini?</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                <h3>Judul</h3>
                <input type="text" id="title" name="title" style="width: 250px; display: block; margin: auto; border-radius: 10px;">
                <p></p>

                <h3>Deskripsi</h3>
                <input type="text" id="description" name="description" style="width: 250px; display: block; margin: auto; height: 60px; border-radius: 10px;">
                <p></p>
            </table>
            <br>
            <button type="submit" class="button">Tambah</button>
        </form>
        <p></p>
        <button type="submit" class="button"><a href="{% url 'todolist:show_todolist' %}">Kembali</a></button>
</div>

<style>
    body {
        background: linear-gradient(45deg, blue, purple,cyan);    
    }

    h3 {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        text-align: center;
        color: white;
    }

    h1 {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        text-align: center;
        color: white;
        text-decoration: underline;
    }
    
    .button {
        margin: auto;
        align-items: center;
        background-color: #a09c9c;
        border: 2px solid #111;
        border-radius: 8px;
        box-sizing: border-box;
        color: #111;
        cursor: pointer;
        display: flex;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        font-size: 16px;
        height: 48px;
        justify-content: center;
        line-height: 24px;
        max-width: 100%;
        padding: 0 25px;
        position: relative;
        text-align: center;
        text-decoration: none;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
    }

    .button:after {
        background-color: #111;
        border-radius: 8px;
        content: "";
        display: block;
        height: 48px;
        left: 0;
        width: 100%;
        position: absolute;
        top: -2px;
        transform: translate(8px, 8px);
        transition: transform .2s ease-out;
        z-index: -1;
    }

    .button:hover:after {
        transform: translate(0, 0);
    }

    .button:active {
        background-color: #ffdeda;
        outline: 0;
    }

    .button:hover {
        outline: 0;
    }

    @media (min-width: 768px) {
        .button {
            padding: 0 40px;
        }
    }

</style>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class = "login";>
        <form method="POST" action="">
            {% csrf_token %}
            <section class="vh-100">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card bg-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <h2 class="mb-3">Login</h2>
                                <h3 class="mb-5 text-black">Enter your username and password!</h3>
                                

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="typeUsernameX">Username</label>
                                    <input type="text" name="username" placeholder="Username" id="typeUsernameX" class="form-control" />
                                </div>

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="typePasswordX">Password</label>
                                    <input type="password" name="password" placeholder="Password" id="typePasswordX" class="form-control" />
                                </div>

                                {% if messages %}
                                <ul>
                                    {% for message in messages %}
                                        <li>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}

                                <button class="submit" type="text">LOGIN</button>
                                <hr class="my-4">
                                <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-black fw-bold">Sign Up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </form>
    </div>
</body>


<style>
    body {
        background-image: url(https://mir-s3-cdn-cf.behance.net/project_modules/fs/d3450c65528257.5af7785ce36d8.gif);
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
  
  <h1>Formulir Registrasi</h1>  

    <form method="POST" >  
        {% csrf_token %}  
        <section class="vh-100">
          <table>  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" name="submit" value="Daftar"/></td>  
            </tr>  
          </table> 
        </section>
    </form>

  {% if messages %}  
      <ul>   
          {% for message in messages %}  
              <li>{{ message }}</li>  
              {% endfor %}  
      </ul>   
  {% endif %}

</div>  

<style>
  body {
      background-image: url(https://i.pinimg.com/originals/ec/06/7d/ec067dda65caeefca881c250b00e131c.gif);
      background-size: cover;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      display: flex;
      color: black;
      font-size: 20px;
  }  
  .login {
      margin: auto;
  }
  h1 {
      text-align: center;
      margin-bottom: 50px;
      margin-top: 50px;
      font-size: 40px;
  }
</style>

{% endblock content %}

todolist/templates/todolist.html
<style>
    a:link { text-decoration: none; }
    a:visited { text-decoration: none; }
    a:hover { text-decoration: none; }
    a:active { text-decoration: none; }
    
    body {
        background-image: url(https://i.pinimg.com/originals/7d/f2/22/7df2227fc0af47f6c7f6f2e4a0ffde4d.gif);
    }
    .navbar {
        font-size: 30px;
    }
    .d-flex h1 {
        font-size: 55px;
        color: white;
        font-weight: bold;
        margin: auto;
    }

</style>

{% extends 'base.html' %}
{% block meta %}

<title>My Todolist</title>

{% endblock meta %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid navbar-dark bg-dark">
            <a class="navbar-brand navbar-dark bg-dark" style="font-size: 30px;">TASK</a>
            <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
              </button>
              <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link navbar-dark bg-dark cursor-pointer" data-bs-toggle="modal" data-bs-target="#modaladd" href="#">Add Task<span class="sr-only navbar-dark bg-dark"></span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:logout' %}">Logout</a>
                    </li>
                  </ul>
              </div>
        </div>
    </nav>
</header>

<body>
    <div class="d-flex justify-content-center mt-5 mb-5 text-center">
        <h1>My To Do List <br>Hello, {{user_name}}!</h1>
    </div>

    <form action="" method="POST" id="tambahTask">  
        {% csrf_token %}  
        <table>  
            <div class="modal fade" id="modaladd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Create New Todolist</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input class="form-control" type="text" id="title" name="title" placeholder="Title" aria-label="Title" aria-describedby="basic-addon1">
                        <br>
                        <input class="form-control" type="text" id="description" name="description" placeholder="Description" aria-label="Description" aria-describedby="basic-addon1">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" id="createBtn">Create</button>
                    </div>
                  </div>
                </div>
              </div>
        </table>
    </form>
    
    <div class="row row-cols-md-3 mx-auto justify-content-center" id="container">

    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function show_card() {
        let todolist = "";
        $.ajax({
            url: "{% url 'todolist:show_json' %}",
            type: "GET",
            dataType: "json",
            success: function(data){
                if(data == 0) {
                    $('#container').html("")
                }
                else {
                    for (i of data){
                        console.log(data)
                        todolist += `
                        <div class="col-auto mb-3">
                            <div class="card border-primary mx-auto" style="width: 18rem; background-color: rgb(67, 65, 65);">
                                <div class="card-body text-light">
                                    <h3 class="card-title">${i.fields.title}</h3>
                                    <h6 class="card-text">${i.fields.date}</h6>
                                    <p class="card-text">Description: ${i.fields.description}</p>
                                    <p class="card-text">Status: ${i.fields.is_finished ? `Selesai`:`Belum Selesai`}</p>
                                    <a class="btn login_btn btn btn-secondary form-control lg mt-3" href="set_status/${i.pk}">Ubah Status</a>
                                    <a class="btn login_btn btn btn-danger form-control lg mt-2" onclick="deleteTask(${i.pk})">Hapus</a>
                                </div>
                            </div>
                        </div>`;
                        $('#container').html(todolist)
                    }
                }
            },
            error: function(data) {
                console.log('Error')
            }
        })
    }

    function deleteTask(pk){
        $.ajax({
            url: `/todolist/delete/${pk}`,
            type: "DELETE",
            success: function(data) {
                console.log(data)
                $(`#${pk}`).remove()
                show_card()
            }
        })
    }

    $(document).on("submit", "#tambahTask", function(e) {
        e.preventDefault();
        $.ajax ({
            url: "{% url 'todolist:add_task_ajax' %}",
            type: "POST",
            dataType:"json",
            data: {
                title:$("#title").val(),
                description:$("#description").val(),
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success: function(data) {
                show_card();
                const inputs = document.querySelectorAll('#title, #description');
                inputs.forEach(input => {
                    input.value = '';
                });
            }
        })
    })

    $(document).ready(function () {
        show_card();
    })
</script>

{% endblock content %}